apiVersion: apps/v1
kind: Deployment
metadata:
  name: containers-everywhere-client-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: containers-everywhere-client
  template:
    metadata:
      labels:
        app: containers-everywhere-client
    spec:
      containers:
      - name: app
        image: '{{ .Values.image.registry }}/{{ .Values.image.clientRepository | lower }}:{{ .Values.image.clientTag }}'
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        ports:
          - containerPort: 80
        env:
          - name: BGN_API_ENDPOINT
            value: http://containers-everywhere-server-service
      imagePullSecrets:
      - name: acr-pull-secret

---

apiVersion: v1
kind: Service
metadata:
  name: containers-everywhere-client-service
spec:
  selector:
    app: containers-everywhere-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: containers-everywhere-client-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /client(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: containers-everywhere-client-service
            port:
              number: 80