# Default values for compute.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  registry:
  appRepository: 
  apiRepository: 
  appTag: latest
  apiTag: latest

replicas: 1

resources:
  requests:
    cpu: 0.5
    memory: 1Gi