apiVersion: apps/v1
kind: Deployment
metadata:
  name: containers-everywhere-app-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: containers-everywhere-app
  template:
    metadata:
      labels:
        app: containers-everywhere-app
    spec:
      containers:
      - name: app
        image: '{{ .Values.image.registry }}/{{ .Values.image.appRepository }}:{{ .Values.image.appTag }}'
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        ports:
          - containerPort: 80
          