apiVersion: apps/v1
kind: Deployment
metadata:
  name: containers-everywhere-app-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: containers-everywhere-app
  template:
    metadata:
      labels:
        app: containers-everywhere-app
    spec:
      containers:
      - name: app
        image: '{{ .Values.image.registry }}/{{ .Values.image.appRepository }}:{{ .Values.image.appTag }}'
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        ports:
          - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: containers-everywhere-app-service
spec:
  selector:
    app: containers-everywhere-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: containers-everywhere-app-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: containers-everywhere-app-service
          servicePort: 80