on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - run: dotnet build ./src/BoardGameNerd.Server/BoardGameNerd.Server.csproj -c Release
        
      - run: dotnet publish ./src/BoardGameNerd.Server/BoardGameNerd.Server.csproj -c Release -o server
        
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: server
          path: server/**
          if-no-files-found: error

      - run: dotnet build ./src/BoardGameNerd.Client/BoardGameNerd.Client.csproj -c Release
        
      - run: dotnet publish ./src/BoardGameNerd.Client/BoardGameNerd.Client.csproj -c Release -o client
        
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: client
          path: client/**
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - uses: cardinalby/export-env-action@v1
      with:
        envFile: .github/workflows/.env    
        expand: true

    - uses: actions/download-artifact@v2.0.8
      with:
        name: server
        path: server

    - uses: actions/download-artifact@v2.0.8
      with:
        name: client
        path: client

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_SERVICE_SERVER_NAME }}
        package: server

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_SERVICE_CLIENT_NAME }}
        package: client

    - run: az logout
