name: Deploy Client Application Container Image to App Service Container

on:
  workflow_run:
    workflows: [Build and Push Client Container to Azure Container Registry]
    types:
      - completed
  workflow_dispatch:
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}