name: Client Build and Deploy to Azure App Service

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "./src/BoardGameNerd.Client/**"
  #     - "./src/BoardGameNerd.Shared/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - run: dotnet build ./src/BoardGameNerd.Client/BoardGameNerd.Client.csproj -c Release
        
      - run: dotnet publish ./src/BoardGameNerd.Client/BoardGameNerd.Client.csproj -c Release -o publish
        
      - uses: actions/upload-artifact@v2.2.2
        with:
          name: publish
          path: publish/**
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v2.0.8
      with:
        name: publish
        path: publish

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.CLIENT_APP_SERVICE_NAME }}
        package: publish
     
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ secrets.CLIENT_APP_SERVICE_NAME }}
        mask-inputs: false
        app-settings-json: '[{ "name": "BGN_API_ENDPOINT", "value": "${{ secrets.CLIENT_APP_SERVICE_API_ENDPOINT }}", "slotSetting": false }]'

    - run: az logout
