name: Deploy Client Application Container Image to Azure Container App

on:
  workflow_run:
    workflows: [Client Container Build and Push to Azure Container Registry]
    types:
      - completed
  workflow_dispatch:
    # inputs:
    #   imageName:
    #     description: Docker image to deploy
    #     required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@main
      - name: Dotenv Action
        id: dotenv  
        uses: falti/dotenv-action@v0.2.7
        with:
          path: .github/workflows/${{ secrets.ENVIRONMENT_FILE }}
          log-variables: true
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        name: deploy
        with:
          deploymentName: client-deploy-to-aca
          subscriptionId: ${{ steps.dotenv.outputs.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ steps.dotenv.outputs.AZURE_RESOURCE_GROUP }}
          template: infra/compute/aca/client/main.bicep
          parameters: |
            containerRegistryName=${{ steps.dotenv.outputs.CONTAINER_REGISTRY_NAME }} imageName=${{ steps.dotenv.outputs.CLIENT_IMAGE_NAME }}:latest storageAccountName=${{ steps.dotenv.outputs.STORAGE_ACCOUNT_NAME }} logAnalyticsWorkspaceName=${{ steps.dotenv.outputs.LOG_ANALYTICS_WORKSPACE_NAME }} appInsightsName=${{ steps.dotenv.outputs.APPLICATION_INSIGHTS_NAME }} serverContainerAppName=${{ steps.dotenv.outputs.SERVER_ACA_NAME }} kubeEnvironmentName=${{ steps.dotenv.outputs.KUBE_ENVIRONMENT_NAME }} containerAppName=${{ steps.dotenv.outputs.CLIENT_ACA_NAME }}
        continue-on-error: true