name: Deploy Client Application Container Image to Azure Kubernetes Service

on:
  workflow_run:
    workflows: [Client Container Build and Push to Azure Container Registry]
    types:
      - completed

  workflow_dispatch:
    # inputs:
    #   imageName:
    #     description: Docker image to deploy
    #     required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@main
      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.3.1
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP}}
          cluster-name: ${{ secrets.AKS_NAME }}
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace containers-everywhere \
            containers-everywhere-client \
            ./infra/compute/aks/client \
            --values ./infra/compute/aks/client/values.yaml \
            --set image.registry=${{ secrets.ACR_LOGIN_SERVER }} \
            --set image.clientRepository=${{ secrets.CLIENT_IMAGE_NAME }} \
            --set image.clientTag=latest
