name: Deploy Client Application Container Image to App Service Container

on:
  workflow_run:
    workflows: [Client Container Build and Push to Azure Container Registry]
    types:
      - completed

  workflow_dispatch:
    # inputs:
    #   imageName:
    #     description: Docker image to deploy
    #     required: true
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/arm-deploy@v1
        name: deploy
        with:
          deploymentName: client-deploy-to-app-service-container
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: infra/compute/appService/client/main.bicep
          parameters: |
            infra/demo.parameters.json containerRegistryName=${{ secrets.CONTAINER_REGISTRY_NAME }} imageName=${{ secrets.CLIENT_IMAGE_NAME }}:latest storageAccountName=${{ secrets.STORAGE_ACCOUNT_NAME }} logAnalyticsWorkspaceName=${{ secrets.LOG_ANALYTICS_WORKSPACE_NAME }} appInsightsName=${{ secrets.APPLICATION_INSIGHTS_NAME }} appServicePlanName=${{ secrets.APP_SERVICE_PLAN_NAME }} serverAppServiceName=${{ secrets.SERVER_APP_SERVICE_NAME }}
