name: Deploy Base Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - uses: cardinalby/export-env-action@v1
        with:
          envFile: .github/workflows/.env    
          expand: true

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  
          
      # - uses: azure/arm-deploy@v1
      #   with:
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     resourceGroupName: ${{ secrets.PRODUCT_ID }}rg
      #     template: scripts/aci.bicep
      #     parameters: productId=${{ secrets.PRODUCT_ID }} apiImage=${{ secrets.PRODUCT_ID }}acr.azurecr.io/bgnserver:latest appImage=${{ secrets.PRODUCT_ID }}acr.azurecr.io/bgnclient:latest

      - run: az logout