name: Deploy initial infrastructure for Board Game Nerd

on:
  push:
    branches:
      - main
    paths:
      - "./.github/workflows/deploy-initial-infra.yml"
      - "./infra/init/**"
      - "./infra/demo.parameters.json"
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: az deployment group create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file ./infra/init/main.bicep --parameters ./infra/demo.parameters.json
      