name: Client Container Deploy to App Service Container

on:
  workflow_dispatch:
   
jobs:
        
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
 
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ secrets.PRODUCT_ID }}conapp
        mask-inputs: false
        app-settings-json: '[{ "name": "BGN_API_ENDPOINT", "value": "https://mjrbgnconapi.azurewebsites.net/" }]'

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.PRODUCT_ID }}conapp
        images: '${{ secrets.ACR_LOGIN_SERVER }}/bgnclient:latest'     
        
    - run: az logout