name: Client Container Deploy to App Service Container

on:
  workflow_dispatch:
   
jobs:
        
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/appservice-settings@v1
      with:
        app-name: ${{ secrets.PRODUCT_ID }}conapp
        mask-inputs: false
        app-settings-json: '[{ "name": "DOCKER_REGISTRY_SERVER_URL", "value": "https://${{ secrets.ACR_LOGIN_SERVER }}" }, { "name": "DOCKER_REGISTRY_SERVER_USERNAME", "value": "${{ secrets.ACR_USER_NAME }}" }, { "name": "DOCKER_REGISTRY_SERVER_PASSWORD", "value": "${{ secrets.ACR_PASSWORD }}" }, { "name": "BGN_API_ENDPOINT", "value": "https://${{ secrets.PRODUCT_ID }}conapi.azurewebsites.net/" }]'

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.PRODUCT_ID }}conapp
        images: '${{ secrets.ACR_LOGIN_SERVER }}/bgnclient:latest'     
        
    - run: az logout