name: Build and deploy ASP.Net Core app to Azure Web App - mjrbgnapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - run: dotnet build ./src/BoardGameNerd.Server/BoardGameNerd.Server.csproj -c Release